### PR TITLE
chore: use npm ci

### PR DESCRIPTION
**Pull request by DanielRuf**
`npm ci` is much faster and is meant for CI. This PR is meant for evaluating the new ci command and testig the performance and compare the logs of Travis CI.

https://docs.npmjs.com/cli/ci
http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

### CODE REVIEW

**Comment by DanielRuf** [comment]
~27s https://travis-ci.org/developit/unfetch/builds/374531736#L1149
~33s https://travis-ci.org/developit/unfetch/builds/374537209#L438

But the overhead of the npm upgrade adds more time so this change may not be so beneficial.

**Comment by developit** [comment]
Hey Daniel - I think if we change the node version to 8 or 10, we could use `npm ci` without the global npm update right? If so we should!

**Comment by DanielRuf** [comment]
`npm ci` is only available in npm 6 which is shipped with Node 10 by default.

**Comment by DanielRuf** [comment]
> It seems like this could be used without any change, as long as there is a package-lock.json file according to the docs docs.travis-ci.com/user/languages/javascript-with-nodejs/#npm-ci-support

I guess you misunderstand this a bit. This just means if there is a lockfile Travis CI will by default run `npm ci` instead of `npm i` if there is no `install` script set.

You still have to upgrade npm.
Only https://github.com/developit/unfetch/pull/72/files#diff-354f30a63fb0907d4ad57269548329e3R7 is probably not needed but more explicit.

**Comment by styfle** [comment]
> You still have to upgrade npm.

Ah, this is the missing piece in the docs.
I forget which version introduced `npm ci`.

**Comment by DanielRuf** [comment]
@developit keep in mind:
> cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

This is the cause for the failing build at the moment. Or we revert the `npm ci` part and use the standard `npm i`.

**Pull request merged**
