### PR TITLE
Add size limit

### LINKED ISSUE #111: Add size-limit
Hey. I think it will be convenient to use [size-limit](https://github.com/ai/size-limit) to control the bundle. If you don't mind, I'll create a pull request

### PR DESCRIPTION
**Pull request by alik0211**
## 1. Use cpy-cli instead cp
`cp` is not available on windows. `cpy-cli` is cross-platform

## 2. Add size-limit
It is convenient to control the package size. I put the limitation only on the polyfill. That will be enough.

This is how it looks in the console:
image

Resolve #111

### CODE REVIEW

**Comment by alik0211** [comment]
cc @developit

**Comment by alik0211** [comment]
cc @joaovieira ?

**Comment by developit** [comment]
Definitely interested in merging this. Only question I had was whether it was for sure necessary to run a second build after `npm test`?  By default Travis is already running `npm run build`.

**Comment by alik0211** [comment]
I'm sorry, I didn't know that Travis runs it by default `npm run build`. Removed this from Travis's config

**Comment by developit** [comment]
Closing since we're using compressed-size-action.

**Pull request closed without merging**
