### PR TITLE
Index refactoring

### PR DESCRIPTION
**Pull request by dimpiax**
added Object.assign for immutable options, refactoring

### CODE REVIEW

**Comment by developit** [comment]
Hate to keep asking questions, but what is the purpose of the Object.assign() on options? It's never mutated.  Btw if you want to chat before opening PR's that might help with communication.  Anywhere is fine, [Twitter](https://twitter.com/_developit)/[Slack](https://preact-slack.now.sh) 🌈

**Comment by dimpiax** [comment]
It makes high copy of object, and protect for mutating object outside.

**Comment by developit** [comment]
Right, just I am not sure what could mutate it?  All the values are accessed synchronously and then the object is ignored thereafter.  It someone mutates it as soon as possible it wouldn't seem to matter?  My concern is that it adds size for a gain I'm not seeing, and that `Object.assign()` isn't supported in IE, where this polyfill is most important.

**Comment by dimpiax** [comment]
You are right:
* increase size (+9 bytes)
* not whole support (babel polyfill solves) 
* it was for potential uses, but cancelled now.

**Comment by developit** [comment]
Cool. I don't normally use `const` since it doesn't add much value, but I might be willing to budge here.

**Comment by dimpiax** [comment]
it's enough good, anywhere eslint setup for it.
Never `var`, just `let` for mutation, `const` – immutation.

**Pull request closed without merging**
