### PR TITLE
Replace binary operation with boolean expression

### PR DESCRIPTION
**Pull request by eprev**
This way it's better :-)

### CODE REVIEW

**Comment by developit** [comment]
Isn't this significantly larger?  I get that it's more obvious, but the point of this library is to be as small as possible.

**Comment by eprev** [comment]
8 bytes.

```
$ npm run size

> unfetch@1.0.0 size /Users/eprev/Downloads/unfetch
> echo "Gzipped Size: $(strip-json-comments --no-whitespace $npm_package_main | gzip-size)"

Gzipped Size: 502
```

```
$ npm run size

> unfetch@1.0.0 size /Users/eprev/Downloads/unfetch2
> echo "Gzipped Size: $(strip-json-comments --no-whitespace $npm_package_main | gzip-size)"

Gzipped Size: 510
```

**Comment by developit** [comment]
This might sound silly, but I can't justify adding weight purely for readability in a codebase like this.  If there was a performance improvement that might be workable, but as it stands I don't think it would make sense.

**Comment by eprev** [comment]
Understood. No problem.

**Comment by developit** [comment]
Thanks a ton for understanding! ❤️

**Pull request closed without merging**
