### PR TITLE
Extract the ponyfill out from unfetch.

### PR DESCRIPTION
**Pull request by tkh44**
This sets up making unfetch available as a module you would use instead of fetch in ALL cases.

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
I mean it's supposed to be a polyfill so idk

**Comment by developit** [comment]
@ForsakenHarmony his use-case seems good: he got bit because the polyfill acted differently than native fetch.  With the ability to force using unfetch even when `fetch` exists, you can test out the polyfill fallback version in a browser that technically doesn't need it.

**Comment by developit** [comment]
@tkh44 Just sitting on this because I want to tweak the build to strip out the intermediary variables that got added by rollup due to the file split.  Should be simple, just gotta find some spare minutes.

**Comment by simonbuerger** [comment]
@developit since you added the `help wanted` label:

The only way I can see you being able to keep the bundle size the same while still allowing this is to move the `typeof fetch=='function' ? fetch.bind() : ` part into the rollup post replace plugin (though you'd have to add it there for esm too then).

Not ideal, but I don't see another way of having both the raw unfetch function available and also not increasing the output size.

If you think this is acceptable, I can make a new pull request

**Comment by jpike88** [comment]
The documentation currently states that this library can be used as a pony fill. This repo has the tag 'ponyfill'.

Because I've used this with the assumption it functions as a ponyfill, it now breaks on other libraries that look for native fetch functionality to seperate one browser from the next.

https://github.com/pouchdb/pouchdb/issues/7085

Would recommend that this is continues to stall, this library is not described as a ponyfill to save others time.

**Comment by developit** [comment]
FWIW I believe Microbundle may actually solve this "out of the box" because it does export remapping. I'm going to try updating this repo to use it instead of the custom Rollup stuff first (or someone else can if you're up for it!), but if that fails this PR seems like the way to go.

**Comment by developit** [comment]
I ended up doing this as part of updating the whole repo to use Microbundle.

**Pull request closed without merging**
