### PR TITLE
RFC: Add isomorphic-unfetch package

### PR DESCRIPTION
**Pull request by developit**
Same repo/project, separate package.  Currently a polyfill, but maybe it'd be better a ponyfill?  `node-fetch` is already set up that way.

```js
import fetch from 'isomorphic-unfetch';

// in node, `fetch()` is node-fetch
// in browser `fetch()` is (fetch || unfetch)
```

/cc @impronunciable @arunoda

### CODE REVIEW

**Comment by arunoda** [comment]
How about the React Native support?
Do we need some special handling?

**Comment by developit** [comment]
@arunoda hmm, not sure - does RN use webpack and look at the `browser` main field?  If so it should work since that's just a webview, right?

**Comment by arunoda** [comment]
@developit It's not using Webpack but something similar. 
I think they do support the browser field: https://github.com/facebook/react-native/issues/9570

And I don't it has a XHR API, but it comes with fetch by default.

**Comment by arunoda** [comment]
It should work I guess.
See: https://github.com/developit/unfetch/blob/master/src/index.js#L1

**Comment by developit** [comment]
Ah nice, that makes sense. funky they wouldn't support XHR, haha.

**Pull request merged**
