### PR TITLE
Include Typescript typings in published package

### LINKED ISSUE #69: NPM Types not working
when using `import fetch from 'unfetch'` types are not found. It seems the types are not included in the npm package ?

### PR DESCRIPTION
**Pull request by resir014**
This should fix Typescript projects being unable to load the included typings.

Fixes #69, #64.

### CODE REVIEW

**Comment by bradleyayers** [comment]
Would be great to get this merged in. What are the next steps here?

**Comment by resir014** [comment]
@bradleyayers Should be done, but not sure why the CI fails. Can @developit help us on this?

**Comment by bradleyayers** [comment]
I've just thrown a temporary `declare module "unfetch";` for now, 🤞🏻this will be released soon. I came across it as this library is suggested by `apollo-link-http` when running under Jest.

**Comment by simonbuerger** [comment]
@resir014 tests failing on master, so it's not just your PR :)

I think @developit is very busy. He's maintaining 100s of repos.

@developit do you need another maintainer? Willing to help out.

**Comment by developit** [comment]
That might be a good idea! My github notifications are unrecoverable at this point TBH, though this repo shouldn't be much of a maintenance burden. If anyone wants to help out (I noticed @styfle and @DanielRuf doing a bunch of lovely work!) hit me up on the [preact slack](https://preact-slack.now.sh) or Twitter and we'll set up collaborators.

**Comment by developit** [comment]
I haven't figured out what's up with the CI build, but there's no way this change is breaking so it's merge time.

**Comment by developit** [comment]
Things should be looking a little peachier now, spent an hour or two cleaning up and cut a [3.1.0 release](https://github.com/developit/unfetch/releases/tag/3.1.0).

**Comment by DanielRuf** [comment]
I'll take a look today probably and check what we can improve or make better and ensure more stable and faster CI jobs.

**Comment by DanielRuf** [comment]
The CI job is failing due to a missing space in the sanity check.

I think this was / is already fixed in master (afaik).

**Comment by DanielRuf** [comment]
See https://github.com/developit/unfetch/pull/73.

**Pull request merged**
