### PR TITLE
Fix polyfill in webpack 2

### LINKED ISSUE #31: unfetch/polyfill doesn’t work in webpack 2
When I do:

```js
import 'unfetch/polyfill';
```

I see this error in Safari 10:

> TypeError: fetch is not a function.

Because `fetch` is actually a ES module wrapper:

```js
{__esModule: true, default: function}
```

I suppose it’s because you have `require('.')` in `polyfll.js` and webpack 2 resolves it to `index.es.js`. So this code works for me:

```js
if (!window.fetch) {
    window.fetch = require('unfetch').default;
}
```

I’d be happy to submit a PR but not sure what would be the right fix for this.

### PR DESCRIPTION
**Pull request by sapegin**
Fix #31 

P. S. Will be able to test in a real project only tomorrow

### CODE REVIEW

**Comment by sapegin** [comment]
Yup, works now! :shipit:

**Comment by developit** [comment]
Merging! Think it'd be worth keeping it as `.` though?  The `.default` bit was the real fix here.

**Comment by developit** [comment]
Released as [2.1.2](https://github.com/developit/unfetch/releases/tag/2.1.2)

**Comment by sapegin** [comment]
Yeah, maybe ;-)

**Pull request merged**
